kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tls
nodes:
  - role: control-plane  
    image: kindest/node:v1.33.1
    kubeadmConfigPatches:
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      address: "127.0.0.1"
  - role: worker
    image: kindest/node:v1.33.1
    kubeadmConfigPatches:
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      address: "127.0.0.1"